/*
 * Generated by JasperReports
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;



/**
 *
 */
public class Cherry_Landscape_154cb9d22bae1488a8ab4e45e307f72108dcd129af2d8d3d409d60066eb2d290 extends JREvaluator
{


    /**
     *
     */
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = ((java.lang.Integer)variable_REPORT_COUNT.getValue())%2 == 0; //$JR_EXPR_ID=0$
                break;
            }
            case 9 : 
            {
                value = new java.util.Date(); //$JR_EXPR_ID=9$
                break;
            }
            case 14 : 
            {
                value = " " + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()); //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = "Page "+((java.lang.Integer)variable_PAGE_NUMBER.getValue())+" of"; //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = new java.util.Date(); //$JR_EXPR_ID=16$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = ((java.lang.Integer)variable_REPORT_COUNT.getOldValue())%2 == 0; //$JR_EXPR_ID=0$
                break;
            }
            case 9 : 
            {
                value = new java.util.Date(); //$JR_EXPR_ID=9$
                break;
            }
            case 14 : 
            {
                value = " " + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()); //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = "Page "+((java.lang.Integer)variable_PAGE_NUMBER.getOldValue())+" of"; //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = new java.util.Date(); //$JR_EXPR_ID=16$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = ((java.lang.Integer)variable_REPORT_COUNT.getEstimatedValue())%2 == 0; //$JR_EXPR_ID=0$
                break;
            }
            case 9 : 
            {
                value = new java.util.Date(); //$JR_EXPR_ID=9$
                break;
            }
            case 14 : 
            {
                value = " " + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()); //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = "Page "+((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue())+" of"; //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = new java.util.Date(); //$JR_EXPR_ID=16$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
